# Generated by Django 5.2.17 on 2026-09-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0002_utilisateur_entreprise_gerant'),
        ('ExpeditionsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_jours', models.IntegerField()),
                ('status', models.CharField(choices=[('refuse', 'Refuse'), ('accepte', 'Accepte'), ('en cours', 'En Cours')], default='en cours', max_length=20)),
                ('date_proposition', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='EntreprisesApp.entreprise')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ExpeditionsApp.expedition')),
            ],
        ),
    ]
