# Generated by Django 5.2.17 on 2026-10-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffresApp', '0001_initial'),
        ('VehiculesApp', '0002_remove_vehicule_offre_alter_vehicule_capacite'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VehiculesApp.vehicule'),
        ),
    ]
