# Generated by Django 5.2.17 on 2026-10-06 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffresApp', '0002_offre_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='delai_jours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Le délai doit être au moins de 1 jour')]),
        ),
        migrations.AlterField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Le prix doit être supérieur à 0')]),
        ),
        migrations.AlterField(
            model_name='offre',
            name='status',
            field=models.CharField(choices=[('proposee', 'Proposee'), ('acceptee', 'Acceptee'), ('refusee', 'Refusee')], default='proposee', max_length=20),
        ),
    ]
