# Generated by Django 5.2.17 on 2026-09-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0002_utilisateur_entreprise_gerant'),
        ('OffresApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=15, unique=True)),
                ('type_vebicule', models.CharField(choices=[('camion porteur', 'Camion Porteur'), ('camionette', 'Camionette'), ('semi-remorque', 'Semi-Remorque'), ('fourgon', 'Fourgon')], default='camionette', max_length=20)),
                ('capacite', models.IntegerField()),
                ('disponibilite', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntreprisesApp.entreprise')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='OffresApp.offre')),
            ],
        ),
    ]
