# Generated by Django 5.2.17 on 2026-10-06 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='offre',
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='capacite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100, 'capacite doit etre superieur a 100')]),
        ),
    ]
