# Generated by Django 5.2.17 on 2026-10-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculesApp', '0002_remove_vehicule_offre_alter_vehicule_capacite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='type_vebicule',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('camionnette', 'Camionnette / utilitaire leger'), ('camion_porteur', 'Camion porteur'), ('semi_remorque', 'Semi-remorque'), ('fourgon', 'Fourgon')], default='camionnette', max_length=20),
        ),
    ]
