# Generated by Django 5.2.17 on 2026-10-06 09:38

import EntreprisesApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0002_utilisateur_entreprise_gerant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'adresse doit contenir au moins 20 caracteres'), django.core.validators.MaxLengthValidator(300, 'adresse doit contenir au plus 300 caracteres')]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='matricule_fiscale',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Le format du matricule fiscale est invalide. Il doit être au format 1234567/A/B/C/123 ou 1234567-A-B-C-123.', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]?\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[EntreprisesApp.models.validate_email]),
        ),
    ]
