# Generated by Django 5.2.17 on 2026-09-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0002_utilisateur_entreprise_gerant'),
    ]

    operations = [
        migrations.CreateModel(
            name='expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_souhaitee', models.DateField()),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en attente', 'En Attente'), ('en cours', 'En Cours'), ('terminee', 'Terminee')], default='en attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='EntreprisesApp.entreprise')),
            ],
        ),
    ]
