# Generated by Django 5.2.17 on 2026-10-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpeditionsApp', '0002_alter_expedition_poids_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('publiee', 'Publiee'), ('attribuee', 'Attribuee'), ('en cours', 'En Cours'), ('terminee', 'Terminee')], default='publiee', max_length=20),
        ),
    ]
